import type { Metadata } from "next";
import { Montserrat, Montserrat_Subrayada, Roboto_Serif } from "next/font/google";
import "./globals.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/Providers";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

const robotoSerif = Roboto_Serif({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

const montseratSerif = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  
  return (
    <SessionProvider session={session}>
      <html lang="ro">
        <body className={montseratSerif.className}>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <Providers>{children}</Providers>
          <Toaster richColors theme="light" closeButton />
        </body>
      </html>
    </SessionProvider>
  );
}
